---
- hosts: all
  gather_facts: false
  tasks:
  - name: Load conditional variables
    include_vars: "hosts.{% if lab == 'true' %}lab.yml{% else %}live.yml.vault{% endif %}"

- hosts: all
  tasks:
  - name: "Set up NTP on the server"
    include_role:
      name: geerlingguy.ntp
    vars:
      ntp_timezone: Europe/London
      ntp_manage_config: true
      ntp_restrict: ['127.0.0.1']
      ntp_servers: ["127.0.0.1 iburst", "ntp0.lon.bitfolk.com", "ntp1.lon.bitfolk.com"]

  - name: "Run lugorguk Common Activities"
    include_role:
      name: lugorguk.common

- hosts: admin.lug.org.uk
  tasks:
  - name: Deploy Specifics for admin.lug.org.uk
    include_tasks: playbooks/admin.yml
