---
Group_ayrshire:
  notes: web site not used. mailing list unused
  established_date: "2013-07-03"
  last_update: "2019-04-01"
  status: Active

  title: Ayrshire
  categories: Scotland
  permalink: lugs/Scotland/Ayrshire/
  location:
    latitude: 55.4545748
    longitude: -4.6576824

  website: http://ayrshire.lug.org.uk
  mailing_list: https://mailman.lug.org.uk/mailman/listinfo/ayrshire/
  contact_address: "{{ protected_email_addresses.ayrshire_lug_lugmaster }}"
  contact: Harjinder Singh

  mailman: ayrshire
  dns_name: ayrshire
  mail_hosting: "{{ default_mx }}"
  email_redirects:
    - target: info
      alias:
      - "{{ protected_email_addresses.ayrshire_lug_contact }}"
    - target: webmaster
      alias:
      - "{{ protected_email_addresses.ayrshire_lug_contact }}"
    - target: lugmaster
      alias:
      - "{{ protected_email_addresses.ayrshire_lug_contact }}"
  web_hosting:
    on: snm
    type: static
