---
lugs_g:
  Glastonbury:
    title: Glastonbury
    website: http://lugog.org.uk
    established_date: "2003-03-01"
    status: Active
    last_update: "2009-12-01"
    categories: South-West
    contact_address: "{{ protected_email_addresses.glastonbury_lug_lugmaster }}"
    contact: Sean Miller
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/glastonbury
    permalink: Glastonbury
    dns_name: glastonbury
    web_hosting:
      via: web-01
      to: https://mailman.lug.org.uk/mailman/listinfo/glastonbury
    mail_hosting: "{{ default_mx }}"

  GloucestershireCotswolds:
    title: Gloucestershire & Cotswolds
    website: https://gloucs.lug.org.uk/
    established_date: "2000-06-01"
    status: Active
    last_update: "2009-12-01"
    categories: South-West
    contact_address: "{{ protected_email_addresses.gloucestershirecotswolds_lug_lugmaster }}"
    contact: Glyn Davies
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/gloucs/
    permalink: Gloucestershire & Cotswolds
    dns_name: gloucs
    extra_dns_records:
    - type: A
      record: 213.138.110.9
    mail_hosting: "{{ default_mx }}"

  GreaterLondon:
    title: Greater London (GLLUG)
    website: http://www.gllug.org.uk
    established_date: "1998-08-01"
    status: Active
    last_update: "2012-06-01"
    categories: London
    contact_address: "{{ protected_email_addresses.gllug_lug_lugmaster }}"
    contact: Matt Copperwaite
    mailing_list: http://mailman.lug.org.uk/mailman/listinfo/gllug
    permalink: Greater London (GLLUG)
    dns_name: gllug
    web_hosting:
      via: snm
    extra_dns_records:
    - type: CNAME
      target: gl
      record: www.gllug.ukfsn.org.
    - type: CNAME
      target: www.gl
      record: www.gllug.ukfsn.org.
    mail_hosting: "{{ default_mx }}"
    email_redirects:
    - target: "{{ protected_email_addresses.gllug_lug_lugmaster }}"
      alias:
      - info
      - webmaster
      - lugmaster
