---
lugs_o:
  Oxford:
    title: Oxford
    website: http://www.oxlug.org
    established_date: "1999-01-01"
    status: Active
    last_update: "2010-04-01"
    categories: South-East
    contact_address: "{{ protected_email_addresses.oxford_lug_contact }}"
    contact: Alasdair G Kergon
    mailing_list: http://lists.oxlug.org/mailman/listinfo/oxlug
    permalink: Oxford
    dns_name: oxford
    web_hosting:
      via: web-01
    mail_hosting: "{{ default_mx }}"
    extra_dns_records:
    - type: CNAME
      target: ox
