---
lugs_s:
  Scottish:
    title: Scottish
    website: http://scotlug.org.uk
    established_date: "1998-02-01"
    status: Active
    last_update: "2009-12-01"
    categories: Scotland
    contact_address: "{{ protected_email_addresses.scottish_lug_lugmaster }}"
    contact: Kenny Duffus
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/scottish/
    permalink: Scottish
    dns_name: scottish
    extra_dns_records:
    - type: CNAME
      record: www.scotlug.org.uk.
    mail_hosting: "{{ default_mx }}"

  SheffieldLinuxUserGroupandBSDUserGroup:
    title: Sheffield Linux User Group and BSD User Group
    website: ''
    established_date: "2003-07-01"
    status: Active
    last_update: "2010-04-01"
    categories: Yorkshire-and-Humber
    contact_address: "{{ protected_email_addresses.slugbug_lug_contact }}"
    contact: Chris Croome
    mailing_list: http://www.email-lists.org/mailman/listinfo/slugbug
    permalink: Sheffield Linux User Group and BSD User Group
    dns_name: slugbug
    extra_dns_records:
    - type: A
      record: 193.201.200.140
    - type: MX
      record: 10 mx0.halon.org.uk.

  Sheffield:
    title: Sheffield
    website: http://www.sheflug.org.uk/
    established_date: "1999-01-01"
    status: Active
    last_update: "2009-12-01"
    categories: Yorkshire-and-Humber
    contact_address: "{{ protected_email_addresses.sheffield_lug_contact }}"
    contact: Richard Ibbotson
    mailing_list: http://sheflug.org.uk/mailman/listinfo/sheflug_sheflug.org.uk
    permalink: Sheffield

  Shropshire:
    title: Shropshire
    website: http://shropshirelug.wordpress.com/
    established_date: "2000-02-01"
    status: Active
    last_update: "2013-11-01"
    categories: West-Midlands
    contact_address: "{{ protected_email_addresses.shropshire_lug_lugmaster }}"
    contact: Dave Harris
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/shropshire
    permalink: Shropshire
    dns_name: shropshire
    web_hosting:
      via: web-01
      to: http://shropshirelug.wordpress.com/
    mail_hosting: "{{ default_mx }}"

  SouthendonSea:
    title: Southend-on-Sea
    website: http://soslug.org
    established_date: "2003-03-01"
    status: Active
    last_update: "2016-12-01"
    categories: South-East
    contact_address: "{{ protected_email_addresses.southendonsea_lug_lugmaster }}"
    contact: Derek Shaw
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/sos/
    permalink: Southend-on-Sea
    dns_name: sos
    extra_dns_records:
    - type: CNAME
      record: wiki.soslug.org.
    mail_hosting: "{{ default_mx }}"

  SouthWales:
    title: South Wales
    website: http://www.swlug.org.uk
    established_date: "2002-01-01"
    status: Active
    last_update: "2013-11-01"
    categories: Wales
    mailing_list: http://mailman.lug.org.uk/mailman/listinfo/swlug/
    permalink: South Wales
    dns_name: southwales
    web_hosting:
      via: web-01
      to: http://www.swlug.org.uk
    mail_hosting: "{{ default_mx }}"

  Staffordshire:
    title: Staffordshire
    website: http://staffslug.org.uk/
    established_date: "1999-03-01"
    status: Active
    last_update: "2010-02-01"
    categories: West-Midlands
    contact_address: "{{ protected_email_addresses.staffordshire_lug_lugmaster }}"
    contact: Dave Roberts
    mailing_list: http://lists.staffslug.org.uk/mailman/listinfo/staffslug
    permalink: Staffordshire
    dns_name: staffs
    web_hosting:
      via: web-01
      to: http://staffslug.org.uk/
    mail_hosting: "{{ default_mx }}"

  Surrey:
    title: Surrey
    website: https://www.surrey.lug.org.uk
    established_date: "2000-02-01"
    status: Active
    last_update: "2010-04-01"
    categories: South-East
    contact_address: "{{ protected_email_addresses.surrey_lug_contact }}"
    contact: Surrey LUG admin team
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/surrey/
    permalink: lugs/South-East/Surrey/
    location:
      latitude: 51.31
      longitude: -0.56
    extra_dns_records:
    - type: A
      record: 85.119.83.158
    - type: CNAME
      target: test.surrey
    - type: CNAME
      target: uat.surrey
    mail_hosting: "{{ default_mx }}"

  Sussex:
    title: Sussex
    website: https://mailman.lug.org.uk/mailman/listinfo/sussex/
    established_date: "1999-04-01"
    status: Active
    last_update: "2010-04-01"
    categories: South-East
    contact_address: "{{ protected_email_addresses.sussex_lug_lugmaster }}"
    contact: Steve Dobson
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/sussex/
    permalink: Sussex
    dns_name: sussex
    web_hosting:
      via: web-01
      to: https://mailman.lug.org.uk/mailman/listinfo/sussex/
    mail_hosting: "{{ default_mx }}"
