---
lugs_d:
  DevonCornwall:
    title: Devon and Cornwall
    website: http://dclug.org.uk/
    established_date: 1999/10
    status: Active
    last_update: 12/2009
    categories: South-West
    url: http://lug.org.uk/node/141
    contact_address: "{{ protected_email_addresses.devoncornwall_lug_lugmaster }}"
    contact: DCLUG
    mailing_list: http://mailman.dcglug.org.uk/listinfo/list
    permalink: Devon and Cornwall

  Dorset:
    title: Dorset
    website: http://dorset.lug.org.uk/wiki/
    established_date: 2000/05
    status: Active
    last_update: 12/2009
    categories: South-West
    url: http://lug.org.uk/node/142
    contact_address: "{{ protected_email_addresses.dorset_lug_contact }}"
    contact: LUG Master
    mailing_list: http://mailman.lug.org.uk/mailman/listinfo/dorset
    permalink: Dorset
    match_type: simple
    dns_name: dorset
    web_hosting: snm
    mail_hosting: mail-in-01
    email_redirects:
    - target: "{{ protected_email_addresses.dorset_lug_lugmaster }}"
      alias:
      - lugmaster
      - postmaster
    - target: "{{ protected_email_addresses.dorset_contact }}"
      alias:
      - ekgbixdi

  Durham:
    title: Durham
    website: http://www.nelug.org.uk
    established_date: 1999/01
    status: Active
    last_update: 12/2009
    categories: North-East
    url: http://lug.org.uk/node/24
    contact_address: "{{ protected_email_addresses.durham_lug_lugmaster }}"
    contact: Richard Patterson
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/nelug/
    permalink: Durham
    dns_name: durham
    web_hosting:
      via: web01
      to: http://www.nelug.org.uk
    extra_dns_records:
    - target: ne
    - target: nelug
