gone_lugs_m:
  Mansfield:
    title: Mansfield
    website: http://www.mansfieldlug.org.uk/
    established_date: "2001-10-01"
    status: Gone
    last_checked: "2017-11-11"
    notes: Web page indicates 2014-01 was last activity.
    last_update: "2010-04-01"
    categories: East-Midlands
    contact_address: "{{ protected_email_addresses.mansfield_lug_lugmaster }}"
    contact: Brent Vardy
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/mansfield/
    permalink: Mansfield
    dns_name: Mansfield
    web_hosting:
      via: "{{ primary_suffix }}"
      to: http://www.mansfieldlug.org.uk/
    mail_hosting: "{{ default_mx }}"

  Menai:
    title: Menai
    website: https://mailman.lug.org.uk/mailman/listinfo/menai/
    established_date: "2002-12-01"
    status: Gone
    notes: Last posting to ML was 2010.
    last_checked: "2017-11-17"
    last_update: "2010-04-01"
    categories: Wales
    contact_address: "{{ protected_email_addresses.menai_lug_lugmaster }}"
    contact: Kevin Donnelly
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/menai/
    permalink: Menai
    dns_name: Menai
    web_hosting:
      via: "{{ primary_suffix }}"
      to: https://mailman.lug.org.uk/mailman/listinfo/menai/
    mail_hosting: "{{ default_mx }}"

  merseyside:
    title: Merseyside LUG
    dns_name: merseyside
    web_hosting: "{{ primary_suffix }}"
    established_date: "2004-07-26"
    contact: Darren Jones
    contact_address: "{{ protected_email_addresses.merseyside_lug_lugmaster }}"
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/merseyside
    notes: Website gone, mailing list last active 2010.
    last_checked: "2017-11-17"

  mgeeks:
    title: Maritime Geeks (Chichester Harbour) LUG
    dns_name: mgeeks
    web_hosting: "{{ primary_suffix }}"
    notes: Website gone.
    last_checked: "2017-11-17"

  moray:
    title: Isle of Moray LUG
    dns_name: moray
    web_hosting: "{{ primary_suffix }}"
    notes: Website gone.
    last_checked: "2017-11-19"