gone_lugs_o:
  obaoss:
    title: Oxford Brookes LUG
    dns_name: obaoss
    web_hosting: "{{ primary_suffix }}"
    notes: Website gone. Mailing list inactive since 2008
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/obaoss
    last_checked: "2017-11-19"

  Orkney:
    title: Orkney
    website: http://orklug.org.uk/
    status: Gone
    last_checked: "2017-11-12"
    notes: DNS does not resolve.
    last_update: "2009-12-01"
    categories: Scotland
    contact_address: "{{ protected_email_addresses.orkney_lug_lugmaster }}"
    contact: Digit Siljrath
    permalink: Orkney

  Ormskirk:
    title: Ormskirk LUG
    dns_name: ormskirk
    web_hosting: "{{ primary_suffix }}"
    notes: Website gone. Mailing list inactive since 2009
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/ormskirk
    last_checked: "2017-11-19"

  Orpington:
    title: Orpington LUG
    dns_name: orpington
    web_hosting: "{{ primary_suffix }}"
    notes: Website gone.
    last_checked: "2017-11-19"