gone_lugs_w:
  Watford:
    title: Watford
    website: https://mailman.lug.org.uk/mailman/listinfo/watford/
    established_date: "2006-01-01"
    status: Gone
    Notes: No website, mailing list inactive since March 2016
    last_checked: "2017-11-12"
    last_update: "2010-04-01"
    categories: London
    contact_address: "{{ protected_email_addresses.watford_lug_lugmaster }}"
    contact: Cliff Deamer
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/watford/
    permalink: Watford
    dns_name: Watford
    web_hosting: "{{ primary_suffix }}"
    mail_hosting: "{{ default_mx }}"

  WestBerkshireNewbury:
    title: West Berkshire - Newbury
    website: ''
    established_date: "2006-01-01"
    status: Gone
    last_checked: "2017-11-12"
    last_update: "2010-04-01"
    categories: South-East
    contact_address: "{{ protected_email_addresses.westberkshire_lug_contact }}"
    contact: Phillip Chandler
    permalink: West Berkshire - Newbury
    dns_name: westberkshire
    web_hosting: "{{ primary_suffix }}"
    staff:
    - Name: Phillip Chandler

  WestLothian:
    title: West Lothian
    website:
    - http://wllug.org.uk
    - http://westlothianlug.org.uk
    established_date: "2011-12-01"
    status: Gone
    last_checked: "2017-11-12"
    notes: wllug.org.uk shows spam. westlothianlug.org.uk is gone. Mailing list last post was 2011.
    last_update: "2011-12-01"
    categories: Scotland
    contact_address: "{{ protected_email_addresses.westlothian_lug_lugmaster }}"
    contact: Keiran Smith
    mailing_list: http://mailman.lug.org.uk/mailman/listinfo/westlothian
    permalink: West Lothian
    dns_name: westlothian
    web_hosting:
      via: "{{ primary_suffix }}"
      to: http://westlothianlug.org.uk

  WiganandStHelens:
    title: Wigan and St. Helens
    website: https://mailman.lug.org.uk/mailman/listinfo/wishlug/
    established_date: "2002-08-01"
    status: Gone
    last_checked: "2017-11-12"
    last_update: "2010-04-01"
    categories: North-West
    contact_address: "{{ protected_email_addresses.wigan_lug_lugmaster }}"
    contact: Paul F. Johnson
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/wishlug/
    permalink: Wigan and St. Helens
    dns_name: wishlug
    web_hosting:
      via: "{{ primary_suffix }}"
      to: https://mailman.lug.org.uk/mailman/listinfo/wishlug/

  Wiltshire:
    dns_name: Wiltshire
    title: Wiltshire LUG
    web_hosting:
      on: snm
      type: static
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/wiltshire
    last_checked: "2017-11-20"
    notes: Website exists but notes that the group has wrapped up meetings. Mailing list last used 2015.

  Wirral:
    title: Wirral LUG
    dns_name: Wirral
    web_hosting:
      on: snm
      type: inactive
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/wirral
    last_checked: "2017-11-20"
    notes: Indicates that the group is orphaned.

  wlv:
    dns_name: "wlv"
    web_hosting: "web-01"
    last_checked: "2017-11-20"
    notes: Website gone.

  Worcester:
    title: Worcester LUG
    website: https://worcester.lug.org.uk/
    established_date: "2000-03-01"
    status: Gone
    last_checked: "2017-11-11"
    notes: DNS fails to resolve
    last_update: "2013-02-01"
    categories: West-Midlands
    contact_address: "{{ protected_email_addresses.worcester_lug_lugmaster }}"
    contact: Leo McArdle
    mailing_list: https://mailman.lug.org.uk/mailman/listinfo/worcester/
    permalink: Worcester
    mail_hosting: "{{ default_mx }}"
    dns_name: worcester
    extra_dns_records:
    - type: A
      record: 46.105.11.23
    - type: CNAME
      target: worcs
    - type: CNAME
      target: www.worcs
    email_redirects:
    - target: "{{ protected_email_addresses.worcester_lug_lugmaster }}"
      aliases:
      - admin
      - lugmaster
      - webmaster
      additional_dns_names:
      - worcs

  wos:
    dns_name: "wos"
    web_hosting: "web-01"
    last_checked: "2017-11-20"
    notes: Website gone.

  wot:
    dns_name: "wot"
    title: "Walton On Thames LUG"
    web_hosting: "web-01"
    last_checked: "2017-11-20"
    notes: Website gone.