---
Group_south_west:
  notes: Website still exists, but shows "closed" in 2004.
  last_checked: "2017-11-20"
  status: Gone

  title: South West LUG

  dns_name: southwest
  web_hosting:
    host: snm
    type: static
