---
Group_cumbria:
  established_date: "2000-11-01"
  last_update: "2009-12-01"
  last_checked: "2017-11-11"
  status: Gone

  title: Cumbria
  categories: North-West
  permalink: lugs/North-West/Cumbria

  website: https://www.cumbria.lug.org.uk/
  mailing_list: https://mailman.lug.org.uk/mailman/listinfo/cumbria/
  contact_address: "{{ protected_email_addresses.cumbria_lug_contact }}"
  contact: David Murphy

  mailman: cumbria
  mail_hosting: "{{ default_mx }}"
  email_redirects:
  - target: "{{ protected_email_addresses.cumbria_lug_lugmaster }}"
    alias: schwuk
  extra_dns_records:
  - type: A
    record: 97.107.131.140
  - type: CNAME
    target: "*.cumbria"

