---
Group_leigh:
  notes: Website redirects to inactive. No active posting to ML.
  established_date: "2014-03-01"
  last_update: "2014-03-01"
  last_checked: "2021-01-27"
  status: Gone

  title: Leigh
  categories: North-West
  permalink: lugs/North-West/Leigh # Fixed

  website: https://leigh.lug.org.uk
  mailing_list: https://mailman.lug.org.uk/mailman/listinfo/leigh
  contact_address: "{{ protected_email_addresses.leigh_lug_lugmaster }}"
  contact: Phil Wyett

  mailman: leigh
  dns_name: leigh
  mail_hosting: "{{ default_mx }}"
  email_redirects:
  - target: "{{ protected_email_addresses.leigh_lug_lugmaster }}"
    alias:
    - info
    - webmaster
    - lugmaster
  web_hosting: 
    host: snm
    type: inactive
