---
Active_and_Inactive_Groups: |-
  {
    {% for this in vars | dict2items %}
      {% if this.key | regex_search('^Group_') is not none %}
        "{{ this.key[6:] }}": {{ lookup('vars', this.key) }},
      {% endif %}{# this.key | regex(group) #}
    {% endfor %}{# this in vars #}
  }
Active_Groups: |-
  {
    {% for this in Active_and_Inactive_Groups | dict2items %}
      {% if this.value.status | default('') | lower == 'active' %}
        "{{ this.key }}": {{ lookup('vars', this.key) }},
      {% endif %}{# this.value.status == 'Active' #}
    {% endfor %}{# this in Active_and_Inactive_Groups #}
  }
Inactive_Groups: |-
  {
    {% for this in Active_and_Inactive_Groups | dict2items %}
      {% if this.value.status | default('') | lower != 'active' %}
        "{{ this.key }}": {{ lookup('vars', this.key) }},
      {% endif %}{# this.value.status == 'Active' #}
    {% endfor %}{# this in Active_and_Inactive_Groups #}
  }
Hosted_Groups: |-
  {
    {% for this in Active_and_Inactive_Groups | dict2items %}
      {% if this.value.dns_name | default('') != '' %}
        "{{ this.key }}": {{ lookup('vars', this.key) }},
      {% endif %}{# this.value.status == 'Active' #}
    {% endfor %}{# this in Active_and_Inactive_Groups #}
  }
