---
Group_blackburn:
  notes: Mailing list inactive since 2011, Website gone.
  last_checked: "2017-11-13"

  title: Blackburn LUG

  mailing_list: https://mailman.lug.org.uk/mailman/listinfo/blackburn/

  mailman: blackburn
