---
Group_blux:
  notes: Listed DNS name taken by oriental owner (thus removed). Not related to Linux since ~2006
  last_update: "2009-12-01"
  last_checked: "2017-11-11"
  status: Gone

  title: B-lux
  categories: Other
  permalink: lugs/Other/B-lux

  contact_address: "{{ protected_email_addresses.blux_lug_lugmaster }}"
  contact: Mike Williams
