---
Group_doncaster_hackspace:
  notes: EMail from Andy 2021-09-03, withdrawn as requested
  established_date: "2020-10-01"
  last_update: "2020-10-01"
  last_update: "2021-12-16"
  status: Gone

  title: Doncaster Hackspace
  categories: Yorkshire-and-Humber
  permalink: lugs/Yorkshire-and-Humber/Doncaster-Hackspace/
  location:
    latitude: 53.52
    longitude: -1.13

  mailing_list: https://mailman.lug.org.uk/mailman/listinfo/doncaster
